# Generated by Django 4.2.29 on 2026-07-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('users', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='email_subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='emails.emailschedule'),
        ),
    ]
